import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../src/web3/abis");
mkdirSync(outDir, { recursive: true });

const SOURCES = [
  ["controllerAbi", "IDreamMarginController"],
  ["vaultAbi", "IDreamMarginVault"],
  ["oracleAbi", "IDreamDexMarkOracle"],
  // Custom errors live in the library, not the interfaces: without this the
  // client cannot decode a revert reason and would fall back to generic copy,
  // which frontend-spec §15 forbids.
  ["errorsAbi", "LibDreamMarginErrors"],
];

for (const [name, artifact] of SOURCES) {
  const path = resolve(here, `../../contracts/out/${artifact}.sol/${artifact}.json`);
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  const body = `// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: contracts/out/${artifact}.sol/${artifact}.json

export const ${name} = ${JSON.stringify(abi, null, 2)} as const;
`;
  writeFileSync(resolve(outDir, `${name}.ts`), body);
  console.log(`wrote ${name}.ts (${abi.length} entries)`);
}
