// SPDX-License-Identifier: MIT
pragma solidity 0.8.34;

/// @title DreamMargin position-risk mathematics tests
/// @author DreamMargin contributors
/// @notice Differentially verifies integer economics and fuzzes conservative properties.
/// @dev Committed JSON vectors are generated by an independent Python Fraction model.

import {
  BookWalk,
  PositionHealth,
  RecoveryValue,
  RiskBookLevel,
  SettlementWaterfall
} from "src/libs/dreammargin/LibPositionRisk.sol";
import {LibDreamMarginErrors} from "src/libs/dreammargin/LibDreamMarginErrors.sol";

import {PositionRiskHarness} from "test/harness/PositionRiskHarness.sol";

import {stdJson} from "forge-std/StdJson.sol";
import {Test} from "forge-std/Test.sol";

// Differential vectors are intentionally iterated through external harness calls.
// Decimal casts consume generator-controlled values restricted to 6 or 18.
// forge-lint: disable-start(calls-loop, unsafe-typecast)

/// @notice Exercises all pure valuation, rounding, health, and loss helpers.
contract LibPositionRiskTest is Test {
  using stdJson for string;

  uint256 private constant _WAD = 1e18;
  uint256 private constant _BPS = 10_000;
  uint256 private constant _ONE = 1e6;
  uint256 private constant _YEAR = 365 days;

  /// @notice Stateless risk-math wrapper.
  PositionRiskHarness private _risk;

  /// @notice Contents of the committed independent reference fixture.
  string private _fixture;

  /// @notice Deploys the harness and loads committed vectors without FFI.
  function setUp() external {
    _risk = new PositionRiskHarness();
    _fixture = vm.readFile("test/reference/position-risk-vectors.json");
  }

  /// @notice Matches 6/18-decimal conversions including one-unit rounding ties.
  function test_differentialDecimalNormalization() external view {
    for (uint256 i = 0; i < 5; ++i) {
      string memory root = string.concat(".normalization[", vm.toString(i), "]");
      uint256 amount = _fixture.readUint(string.concat(root, ".amount"));
      uint8 fromDecimals = uint8(_fixture.readUint(string.concat(root, ".from")));
      uint8 toDecimals = uint8(_fixture.readUint(string.concat(root, ".to")));
      assertEq(
        _risk.normalizeDown(amount, fromDecimals, toDecimals),
        _fixture.readUint(string.concat(root, ".down"))
      );
      assertEq(
        _risk.normalizeUp(amount, fromDecimals, toDecimals),
        _fixture.readUint(string.concat(root, ".up"))
      );
    }
  }

  /// @notice Matches independent upward debt conversion at exact and inexact boundaries.
  function test_differentialDebtAssets() external view {
    for (uint256 i = 0; i < 3; ++i) {
      string memory root = string.concat(".debt[", vm.toString(i), "]");
      uint256 shares = _fixture.readUint(string.concat(root, ".shares"));
      uint256 index = _fixture.readUint(string.concat(root, ".index"));
      assertEq(
        _risk.debtAssetsUp(shares, index), _fixture.readUint(string.concat(root, ".assets_up"))
      );
      assertEq(
        _risk.debtSharesDown(_fixture.readUint(string.concat(root, ".assets_up")), index),
        _fixture.readUint(string.concat(root, ".shares_down"))
      );
    }
  }

  /// @notice Matches independent simple-index accrual from one second through ten years.
  function test_differentialDebtIndexAccrual() external view {
    for (uint256 i = 0; i < 4; ++i) {
      string memory root = string.concat(".interest[", vm.toString(i), "]");
      assertEq(
        _risk.accrueDebtIndexUp(
          _fixture.readUint(string.concat(root, ".index")),
          _fixture.readUint(string.concat(root, ".rate")),
          _fixture.readUint(string.concat(root, ".elapsed"))
        ),
        _fixture.readUint(string.concat(root, ".next"))
      );
    }
    for (uint256 i = 0; i < 3; ++i) {
      string memory root = string.concat(".leveraged_execution[", vm.toString(i), "]");
      assertEq(
        _risk.targetDebtAtLimitDown(
          _fixture.readUint(string.concat(root, ".equity")),
          _fixture.readUint(string.concat(root, ".leverage_bps")),
          _fixture.readUint(string.concat(root, ".mark_price")),
          _fixture.readUint(string.concat(root, ".limit_side_price"))
        ),
        _fixture.readUint(string.concat(root, ".target_debt"))
      );
    }
  }

  /// @notice Matches independent empty, dust, single-level, multi-level, and incomplete walks.
  function test_differentialExecutableBookWalks() external view {
    RiskBookLevel[] memory bids = _levels(".book_levels.bids");
    RiskBookLevel[] memory asks = _levels(".book_levels.asks");
    for (uint256 i = 0; i < 5; ++i) {
      string memory root = string.concat(".books[", vm.toString(i), "]");
      uint256 quantity = _fixture.readUint(string.concat(root, ".quantity"));
      BookWalk memory bid = _risk.walkBids(bids, quantity, _ONE);
      BookWalk memory ask = _risk.walkAsks(asks, quantity, _ONE);
      _assertWalk(bid, string.concat(root, ".bid"));
      _assertWalk(ask, string.concat(root, ".ask"));
    }
  }

  /// @notice Matches independent expiry boundaries and terminal payout fee rounding.
  function test_differentialExpiryAndPayout() external view {
    for (uint256 i = 0; i < 5; ++i) {
      string memory root = string.concat(".maintenance[", vm.toString(i), "]");
      assertEq(
        _risk.maintenance(7_500, _fixture.readUint(string.concat(root, ".remaining")), 3_600),
        _fixture.readUint(string.concat(root, ".current"))
      );
    }
    for (uint256 i = 0; i < 4; ++i) {
      string memory root = string.concat(".payout[", vm.toString(i), "]");
      assertEq(
        _risk.terminalPayout(
          _fixture.readUint(string.concat(root, ".shares")),
          _ONE,
          _fixture.readUint(string.concat(root, ".numerator")),
          _fixture.readUint(string.concat(root, ".denominator")),
          _fixture.readUint(string.concat(root, ".fee")),
          _ONE
        ),
        _fixture.readUint(string.concat(root, ".net"))
      );
    }
  }

  /// @notice Matches independent vault-share, leverage, and liquidation rounding vectors.
  function test_differentialVaultLeverageAndLiquidation() external view {
    for (uint256 i = 0; i < 3; ++i) {
      string memory root = string.concat(".vault[", vm.toString(i), "]");
      (uint256 sharesDown, uint256 sharesUp, uint256 assetsDown, uint256 assetsUp) = _risk.vaultConversions(
        _fixture.readUint(string.concat(root, ".amount")),
        _fixture.readUint(string.concat(root, ".supply")),
        _fixture.readUint(string.concat(root, ".assets")),
        _fixture.readUint(string.concat(root, ".virtual_shares")),
        _fixture.readUint(string.concat(root, ".virtual_assets"))
      );
      assertEq(sharesDown, _fixture.readUint(string.concat(root, ".shares_down")));
      assertEq(sharesUp, _fixture.readUint(string.concat(root, ".shares_up")));
      assertEq(assetsDown, _fixture.readUint(string.concat(root, ".assets_down")));
      assertEq(assetsUp, _fixture.readUint(string.concat(root, ".assets_up")));
    }
    for (uint256 i = 0; i < 4; ++i) {
      string memory root = string.concat(".leverage[", vm.toString(i), "]");
      assertEq(
        _risk.targetDebtDown(
          _fixture.readUint(string.concat(root, ".equity")),
          _fixture.readUint(string.concat(root, ".leverage_bps"))
        ),
        _fixture.readUint(string.concat(root, ".target_debt"))
      );
    }
    for (uint256 i = 0; i < 3; ++i) {
      string memory root = string.concat(".liquidation[", vm.toString(i), "]");
      assertEq(
        _risk.liquidationShares(
          _fixture.readUint(string.concat(root, ".debt")),
          _fixture.readUint(string.concat(root, ".bonus")),
          _fixture.readUint(string.concat(root, ".price")),
          _ONE,
          _fixture.readUint(string.concat(root, ".available"))
        ),
        _fixture.readUint(string.concat(root, ".seized"))
      );
    }
  }

  /// @notice Verifies inclusive caps, cumulative TWAP, and exact grid boundaries.
  function test_capTwapAndQuantizationBoundaries() external view {
    assertTrue(_risk.withinDebtCap(60, 40, 100));
    assertFalse(_risk.withinDebtCap(61, 40, 100));
    assertFalse(_risk.withinDebtCap(type(uint256).max, 1, type(uint256).max));
    assertEq(_risk.cumulativeTwap(1_000, 4_603, 6), 600);
    (uint256 down, uint256 up) = _risk.quantize(1_000, 100);
    assertEq(down, 1_000);
    assertEq(up, 1_000);
    (down, up) = _risk.quantize(1_001, 100);
    assertEq(down, 1_000);
    assertEq(up, 1_100);
  }

  /// @notice Demonstrates executable-route selection followed by the mature mark cap.
  function test_recoveryUsesBestCompleteRouteThenTwapCap() external view {
    BookWalk memory direct = _risk.walkBids(_levels(".book_levels.bids"), 4 * _ONE, _ONE);
    BookWalk memory opposite = _risk.walkAsks(_levels(".book_levels.asks"), 4 * _ONE, _ONE);
    RecoveryValue memory recovery =
      _risk.recovery(4 * _ONE, direct, opposite, _ONE, 100, 580_000, 8_000, _ONE);

    assertEq(recovery.directRecovery, 2_300_000);
    assertEq(recovery.hedgeRecovery, 2_459_996);
    assertEq(recovery.routeRecovery, 2_459_996);
    assertEq(recovery.markCap, 1_856_000);
    assertEq(recovery.liquidationValue, 1_856_000);
  }

  /// @notice Values incomplete visible depth at zero for that route.
  function test_incompleteBookRouteHasZeroRecovery() external view {
    RiskBookLevel[] memory empty = new RiskBookLevel[](0);
    BookWalk memory direct = _risk.walkBids(empty, _ONE, _ONE);
    BookWalk memory opposite = _risk.walkAsks(empty, _ONE, _ONE);
    RecoveryValue memory recovery =
      _risk.recovery(_ONE, direct, opposite, _ONE, 0, 500_000, _BPS, _ONE);
    assertEq(recovery.directRecovery, 0);
    assertEq(recovery.hedgeRecovery, 0);
    assertEq(recovery.liquidationValue, 0);
  }

  /// @notice Explains healthy, underwater, debt-free, and zero-value health encodings.
  function test_positionHealthBoundaries() external view {
    PositionHealth memory healthy = _risk.health(2_000_000, 1_000_000);
    assertEq(healthy.equity, 1_000_000);
    assertEq(healthy.ltvBps, 5_000);
    assertEq(healthy.leverageBps, 20_000);

    PositionHealth memory underwater = _risk.health(999_999, 1_000_000);
    assertEq(underwater.equity, 0);
    assertEq(underwater.leverageBps, type(uint256).max);
    PositionHealth memory empty = _risk.health(0, 0);
    assertEq(empty.ltvBps, 0);
    assertEq(empty.leverageBps, 0);
  }

  /// @notice Proves virtual offsets make the first deposit defined and preserve rounding direction.
  function test_virtualVaultConversionsProtectRounding() external view {
    (uint256 sharesDown, uint256 sharesUp, uint256 assetsDown, uint256 assetsUp) =
      _risk.vaultConversions(7, 0, 0, _ONE, 1);
    assertEq(sharesDown, 7 * _ONE);
    assertEq(sharesUp, 7 * _ONE);
    assertEq(assetsDown, 0);
    assertEq(assetsUp, 1);

    (sharesDown, sharesUp, assetsDown, assetsUp) = _risk.vaultConversions(7, 11, 13, 1, 1);
    assertLe(sharesDown, sharesUp);
    assertLe(assetsDown, assetsUp);
  }

  /// @notice Applies fee waiver before reserve and reports only the remaining senior loss.
  function test_settlementWaterfallDoesNotDoubleCountLoss() external view {
    SettlementWaterfall memory loss = _risk.waterfall(400, 1_000, 100, 250);
    assertEq(loss.repaidAssets, 400);
    assertEq(loss.feesWaived, 100);
    assertEq(loss.reserveUsed, 250);
    assertEq(loss.badDebt, 250);
    assertEq(loss.ownerAssets, 0);

    SettlementWaterfall memory surplus = _risk.waterfall(1_200, 1_000, 100, 250);
    assertEq(surplus.repaidAssets, 1_000);
    assertEq(surplus.ownerAssets, 200);
    assertEq(surplus.badDebt, 0);
  }

  /// @notice Rejects a nonzero action that venue quantization would erase.
  function test_quantizationRejectsNonzeroDust() external {
    vm.expectRevert(abi.encodeWithSelector(LibDreamMarginErrors.QuantizedToZero.selector, 99, 100));
    // The call is expected to revert before returning either quantized value.
    // forge-lint: disable-next-line(unused-return)
    _risk.quantize(99, 100);
  }

  /// @notice Fuzzes opposite debt-rounding directions around every multiplication remainder.
  /// @param shares Seed debt-share quantity.
  /// @param indexSeed Seed debt index increment.
  function testFuzz_debtRoundingNeverUnderstates(uint128 shares, uint96 indexSeed) external view {
    uint256 index = _WAD + uint256(indexSeed);
    uint256 assetsUp = _risk.debtAssetsUp(shares, index);
    uint256 sharesUp = _risk.debtSharesUp(assetsUp, index);
    assertGe(sharesUp, shares);
    if (shares != 0) assertGt(assetsUp, 0);
  }

  /// @notice Fuzzes monotonic expiry compression across two ordered remaining times.
  /// @param a First remaining-time seed.
  /// @param b Second remaining-time seed.
  /// @param baseSeed Base maintenance-LTV seed.
  function testFuzz_expiryCompressionNeverLoosens(uint32 a, uint32 b, uint16 baseSeed)
    external
    view
  {
    uint256 earlier = bound(a, 0, 30 days);
    uint256 later = bound(b, earlier, 30 days);
    uint256 base = bound(baseSeed, 0, _BPS);
    uint256 nearExpiry = _risk.maintenance(base, earlier, 7 days);
    uint256 farFromExpiry = _risk.maintenance(base, later, 7 days);
    assertLe(nearExpiry, farFromExpiry);
    assertLe(farFromExpiry, base);
  }

  /// @notice Fuzzes liquidation rounding and the hard available-share cap.
  /// @param debtSeed Debt seed.
  /// @param priceSeed Unit-price seed.
  /// @param availableSeed Available-share seed.
  function testFuzz_liquidationSeizureNeverExceedsCustody(
    uint96 debtSeed,
    uint96 priceSeed,
    uint96 availableSeed
  ) external view {
    uint256 price = bound(priceSeed, 1, _ONE);
    uint256 available = uint256(availableSeed);
    uint256 seized = _risk.liquidationShares(debtSeed, 1_000, price, _ONE, available);
    assertLe(seized, available);
  }

  /// @notice Loads the three normalized levels from one fixture book side.
  /// @param root JSON path to the level array.
  /// @return levels Normalized risk-book levels.
  function _levels(string memory root) private view returns (RiskBookLevel[] memory levels) {
    levels = new RiskBookLevel[](3);
    for (uint256 i = 0; i < 3; ++i) {
      string memory item = string.concat(root, "[", vm.toString(i), "]");
      levels[i] = RiskBookLevel({
        price: _fixture.readUint(string.concat(item, ".price")),
        quantity: _fixture.readUint(string.concat(item, ".quantity"))
      });
    }
  }

  /// @notice Compares one Solidity walk to an independently generated fixture object.
  /// @param walk Solidity walk result.
  /// @param root JSON path to the expected result.
  function _assertWalk(BookWalk memory walk, string memory root) private view {
    assertEq(walk.value, _fixture.readUint(string.concat(root, ".value")));
    assertEq(walk.filledQuantity, _fixture.readUint(string.concat(root, ".filled")));
    assertEq(walk.averagePrice, _fixture.readUint(string.concat(root, ".average")));
    assertEq(walk.complete, _fixture.readBool(string.concat(root, ".complete")));
  }
}

// forge-lint: disable-end(calls-loop, unsafe-typecast)
