// GENERATED by scripts/generate-deployment.mjs — do not edit.
// Source: contracts/deployments/shannon-deployment.json
// Regenerate with: npm run generate:deployment

/** Immutable dreammargin deployment bindings on Somnia Shannon. */
export const DEPLOYMENT = {
  chainId: 50312,
  deployedAtBlock: 478284318n,
  controller: "0x50B054bD4A891C44A66c86e8c82A45AE0630869c",
  vault: "0xE4B62C03b4a618f5713C6f0b06F6bB763e7685a6",
  oracle: "0x278aDFBF3D6906fb17616cFA35a3c11A3dDA93d1",
  module: "0x3ecC694Cef705358864a646142ac17A90E29e388",
  collateral: "0x70a86D8842FB63C4Ad2b7cdddF530eBf1BB25d8E",
  outcomeToken: "0xB52c5934113Af5c0Bb20eb3C72290C8215f755b9",
} as const;

export type Deployment = typeof DEPLOYMENT;
