// GENERATED by scripts/generate-deployment.mjs — do not edit.
// Sources: contracts/deployments/shannon-deployment.json and shannon-frontend.json
// Regenerate with: npm run generate:deployment

/** Immutable DreamMargin deployment bindings on Somnia Shannon. */
export const DEPLOYMENT = {
  chainId: 50312,
  deployedAtBlock: 479866354n,
  controller: "0xc141ba0c4f7bFAa72628f6Ea28F6e0118F154fe3",
  vault: "0x97cE780455c04398c6b4b079Dbb3F434619F8027",
  oracle: "0x979ADc628D88fb0499F0108C0968433B48b9259C",
  reactiveObserver: "0x117189C8ab4c6Aeb07Cc2c863c724A154ECBb1A5",
  seriesPolicyId: "0x8a2256ecf5f0225a38c67e560c1157ab952e4a72f46da40fcb7196373bd0ea7c",
  module: "0x3ecC694Cef705358864a646142ac17A90E29e388",
  collateral: "0x70a86D8842FB63C4Ad2b7cdddF530eBf1BB25d8E",
  outcomeToken: "0xB52c5934113Af5c0Bb20eb3C72290C8215f755b9",
  collateralDecimals: 6,
  maxPositionPageSize: 100,
} as const;

/** Dedicated, long-lived DreamDEX generations supported by this client. */
export const MARKETS = [
  {
    symbol: "BTC",
    question: "BTC closes at or above its opening price",
    marketId: "0x0000000000000000000000000000000000000000000000000000000000013b54",
    market: "0x8Ed1Eb342adFf420d30ee000492746bdc09fB927",
    pool: "0x36c22823B8C08b6546c5De439aa941EA73aA9b5a",
    marketNonce: 1n,
    yesId: 1476284217057947301316217726535737061022363815369631198127616553910528n,
    noId: 1476284217057947301316217726535737061022363815369631198127616553910529n,
    yesGenerationKey: "0x26d84ba32cf58cf15aeb7904cd8b120eef92824bd9aa363d091fe3b68ad81ebd",
    noGenerationKey: "0x80fc98b1d401834441347604ee42bc028554b6414119f3f799d77c59a6979224",
    tradingStart: 1788563732n,
    expiry: 1792368000n,
  },
  {
    symbol: "ETH",
    question: "ETH closes at or above its opening price",
    marketId: "0x0000000000000000000000000000000000000000000000000000000000013b55",
    market: "0x161c6198c44D24E2D78A6dEf37Af9B5106AdEd98",
    pool: "0xC5Fa5aA238977bcC7C05290De2F1714b11559027",
    marketNonce: 1n,
    yesId: 5337474850877550297290828291937645639666702779093185437515453097312512n,
    noId: 5337474850877550297290828291937645639666702779093185437515453097312513n,
    yesGenerationKey: "0x35f65a6bf318a5cb403b467e397fab9a0f2d3a0239551e466ec4f39050a9abdf",
    noGenerationKey: "0xa728121e5141ee0c2a66e15da13f3bbcf73b63c3112ce60ea997c0093a93e82e",
    tradingStart: 1788563738n,
    expiry: 1792368000n,
  },
] as const;

export type Deployment = typeof DEPLOYMENT;
export type MarketDeployment = (typeof MARKETS)[number];
