// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: contracts/out/IDreamMarginController.sol/IDreamMarginController.json

export const controllerAbi = [
  {
    type: "function",
    name: "activateSeriesGeneration",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct MarketKey",
        components: [
          {
            name: "marketId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "pool",
            type: "address",
            internalType: "address",
          },
          {
            name: "marketNonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "outcomeToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "outcomeId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "collateral",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        name: "outcomeIndex",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    outputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addCollateral",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "shares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "close",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IDreamMarginController.CloseParams",
        components: [
          {
            name: "positionId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxRepayAssets",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minCollateralOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limitPrice",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "orderType",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "withdrawOutcome",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "assetsOut",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "sharesOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deleverage",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IDreamMarginController.DeleverageParams",
        components: [
          {
            name: "positionId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sharesToSell",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minCollateralOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limitPrice",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "orderType",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "sharesSold",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "assetsRepaid",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeGenerationChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "config",
        type: "tuple",
        internalType: "struct GenerationConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "marketGroup",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
      {
        name: "oracleConfig",
        type: "tuple",
        internalType: "struct OracleConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "minAge",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "updateInterval",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "staleAfter",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "depthQuantity",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "maxObservations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "maxBookLevels",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeGlobalRiskChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "config",
        type: "tuple",
        internalType: "struct GlobalRiskConfig",
        components: [
          {
            name: "maxDebtGlobal",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxDailyRealizedLoss",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxVaultUtilizationBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "governanceDelay",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "lossWindow",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "lossCooldown",
            type: "uint40",
            internalType: "uint40",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeModeChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "mode",
        type: "uint8",
        internalType: "enum ProtocolMode",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeReserveWithdrawal",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "assets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "reserveSharesBurned",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeRoleChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "roles",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "executeSeriesPolicyChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policy",
        type: "tuple",
        internalType: "struct SeriesPolicy",
        components: [
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "originVenueId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "originOperatorId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "collateral",
            type: "address",
            internalType: "address",
          },
          {
            name: "minIntervalSec",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "oracle",
            type: "tuple",
            internalType: "struct SeriesOracleConfig",
            components: [
              {
                name: "minAge",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "updateInterval",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "staleAfter",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "depthQuantity",
                type: "uint128",
                internalType: "uint128",
              },
              {
                name: "maxObservations",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
            ],
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [
      {
        name: "recipient",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "freezeGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "freezeSeriesPolicy",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fundReserve",
    inputs: [
      {
        name: "assets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "reserveShares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct GenerationConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "marketGroup",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPosition",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "position",
        type: "tuple",
        internalType: "struct Position",
        components: [
          {
            name: "owner",
            type: "address",
            internalType: "address",
          },
          {
            name: "marketId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "pool",
            type: "address",
            internalType: "address",
          },
          {
            name: "outcomeToken",
            type: "address",
            internalType: "address",
          },
          {
            name: "outcomeId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "shares",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "debtShares",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "initialEquity",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "marketNonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "openedAt",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "expiry",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "outcomeIndex",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum PositionStatus",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSeriesPolicy",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "policy",
        type: "tuple",
        internalType: "struct SeriesPolicy",
        components: [
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "originVenueId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "originOperatorId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "collateral",
            type: "address",
            internalType: "address",
          },
          {
            name: "minIntervalSec",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "oracle",
            type: "tuple",
            internalType: "struct SeriesOracleConfig",
            components: [
              {
                name: "minAge",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "updateInterval",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "staleAfter",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "depthQuantity",
                type: "uint128",
                internalType: "uint128",
              },
              {
                name: "maxObservations",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
            ],
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "globalRiskConfig",
    inputs: [],
    outputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct GlobalRiskConfig",
        components: [
          {
            name: "maxDebtGlobal",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxDailyRealizedLoss",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxVaultUtilizationBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "governanceDelay",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "lossWindow",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "lossCooldown",
            type: "uint40",
            internalType: "uint40",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidate",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IDreamMarginController.LiquidationParams",
        components: [
          {
            name: "positionId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maxDebtAssets",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minSharesOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minCollateralOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limitPrice",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "orderType",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "route",
            type: "uint8",
            internalType: "enum IDreamMarginController.LiquidationRoute",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "repaid",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "seized",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "incentive",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lossState",
    inputs: [],
    outputs: [
      {
        name: "dailyLoss",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "windowStartedAt",
        type: "uint40",
        internalType: "uint40",
      },
      {
        name: "reduceOnlyTriggeredAt",
        type: "uint40",
        internalType: "uint40",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "module",
    inputs: [],
    outputs: [
      {
        name: "module_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openPosition",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct IDreamMarginController.OpenParams",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "outcomeIndex",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "initialShares",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "leverageBps",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "maxCollateralIn",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minSharesOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limitPrice",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "orderType",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "sharesBought",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "debtAssets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "oracle",
    inputs: [],
    outputs: [
      {
        name: "oracle_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "policyFor",
    inputs: [
      {
        name: "marketId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "eligible",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "policyForGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionCloseFacet",
    inputs: [],
    outputs: [
      {
        name: "facet",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionLiquidationFacet",
    inputs: [],
    outputs: [
      {
        name: "facet",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionOpenFacet",
    inputs: [],
    outputs: [
      {
        name: "facet",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionSettlementFacet",
    inputs: [],
    outputs: [
      {
        name: "facet",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positionsOf",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
      {
        name: "offset",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "limit",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "ids",
        type: "uint256[]",
        internalType: "uint256[]",
      },
      {
        name: "total",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolMode",
    inputs: [],
    outputs: [
      {
        name: "mode",
        type: "uint8",
        internalType: "enum ProtocolMode",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recordRecovery",
    inputs: [
      {
        name: "assets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maxAssets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "assetsRepaid",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rolesOf",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "roles",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "scheduleChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "payloadHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "scheduleGenerationChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "config",
        type: "tuple",
        internalType: "struct GenerationConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "marketGroup",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
      {
        name: "oracleConfig",
        type: "tuple",
        internalType: "struct OracleConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "minAge",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "updateInterval",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "staleAfter",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "depthQuantity",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "maxObservations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "maxBookLevels",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "scheduleSeriesPolicyChange",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policy",
        type: "tuple",
        internalType: "struct SeriesPolicy",
        components: [
          {
            name: "creator",
            type: "address",
            internalType: "address",
          },
          {
            name: "originVenueId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "originOperatorId",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "collateral",
            type: "address",
            internalType: "address",
          },
          {
            name: "minIntervalSec",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "risk",
            type: "tuple",
            internalType: "struct RiskConfig",
            components: [
              {
                name: "maxDebtPerPosition",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerOutcome",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "maxDebtPerMarket",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "minDebt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "initialLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maintenanceLtvBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralFactorBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "liquidationBonusBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSpreadBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxSlippageBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxPositionDepthBps",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxLeverageBps",
                type: "uint32",
                internalType: "uint32",
              },
              {
                name: "openingCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "reduceOnlyCutoff",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "compressionWindow",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "collateralDecimals",
                type: "uint8",
                internalType: "uint8",
              },
              {
                name: "outcomeIndex",
                type: "uint8",
                internalType: "uint8",
              },
            ],
          },
          {
            name: "oracle",
            type: "tuple",
            internalType: "struct SeriesOracleConfig",
            components: [
              {
                name: "minAge",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "updateInterval",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "staleAfter",
                type: "uint40",
                internalType: "uint40",
              },
              {
                name: "depthQuantity",
                type: "uint128",
                internalType: "uint128",
              },
              {
                name: "maxObservations",
                type: "uint16",
                internalType: "uint16",
              },
              {
                name: "maxBookLevels",
                type: "uint16",
                internalType: "uint16",
              },
            ],
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "frozen",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEmergencyMode",
    inputs: [
      {
        name: "mode",
        type: "uint8",
        internalType: "enum ProtocolMode",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settle",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "repaid",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "ownerAssets",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "badDebt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [
      {
        name: "vault_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawCollateral",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "shares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BadDebtRecovered",
    inputs: [
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChangeCancelled",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChangeExecuted",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "payloadHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChangeScheduled",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "payloadHash",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "executableAt",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CollateralAdded",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "shares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CollateralWithdrawn",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "shares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GenerationFrozen",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GenerationUpdated",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "enabled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "frozen",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionClosed",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assetsOut",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "sharesOut",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionDeleveraged",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "sharesSold",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "assetsRepaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionLiquidated",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "liquidator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "route",
        type: "uint8",
        indexed: false,
        internalType: "enum IDreamMarginController.LiquidationRoute",
      },
      {
        name: "repaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "seized",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "incentive",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionOpened",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "initialShares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "sharesBought",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "debtAssets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionRepaid",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assetsRepaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "debtSharesRepaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PositionSettled",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "repaid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "ownerAssets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "badDebt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolModeUpdated",
    inputs: [
      {
        name: "previousMode",
        type: "uint8",
        indexed: true,
        internalType: "enum ProtocolMode",
      },
      {
        name: "newMode",
        type: "uint8",
        indexed: true,
        internalType: "enum ProtocolMode",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProtocolReserveWithdrawn",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveSharesBurned",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReserveFunded",
    inputs: [
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reserveShares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RolesUpdated",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "previousRoles",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newRoles",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SeriesGenerationActivated",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "policyId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "marketGroup",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "outcomeIndex",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SeriesPolicyFrozen",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SeriesPolicyUpdated",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "identity",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "enabled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "frozen",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
] as const;
