// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: contracts/out/LibDreamMarginErrors.sol/LibDreamMarginErrors.json

export const errorsAbi = [
  {
    type: "error",
    name: "ActionBlocked",
    inputs: [
      {
        name: "mode",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "action",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
  },
  {
    type: "error",
    name: "AlreadyInitialized",
    inputs: [
      {
        name: "initialized",
        type: "bool",
        internalType: "bool",
      },
    ],
  },
  {
    type: "error",
    name: "BalanceDeltaMismatch",
    inputs: [
      {
        name: "asset",
        type: "address",
        internalType: "address",
      },
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actual",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ChangeAlreadyScheduled",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "ChangeNotReady",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "executableAt",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "currentTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ChangeNotScheduled",
    inputs: [
      {
        name: "changeId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "ChangePayloadMismatch",
    inputs: [
      {
        name: "expectedHash",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "actualHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "DeadlineExpired",
    inputs: [
      {
        name: "deadline",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "currentTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "DebtCapExceeded",
    inputs: [
      {
        name: "scope",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "resultingDebt",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximumDebt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ExcessiveCollateralIn",
    inputs: [
      {
        name: "spent",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "GenerationAlreadyConfigured",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "GenerationFrozen",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "GenerationMismatch",
    inputs: [
      {
        name: "expectedKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "actualKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "IncompleteClose",
    inputs: [
      {
        name: "remainingShares",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "remainingDebtShares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientBookDepth",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "filledQuantity",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "requiredQuantity",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientDebtShares",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientHealth",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "requiredValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientLiquidity",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientOutcomeAllowance",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "outcomeId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientPositionShares",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientShareAllowance",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientSharesOut",
    inputs: [
      {
        name: "received",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientVaultShares",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "IntegrationValueMismatch",
    inputs: [
      {
        name: "field",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "expected",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "actual",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidBook",
    inputs: [
      {
        name: "pool",
        type: "address",
        internalType: "address",
      },
      {
        name: "bidPrice",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "askPrice",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidBps",
    inputs: [
      {
        name: "field",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidFacet",
    inputs: [
      {
        name: "facet",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidLot",
    inputs: [
      {
        name: "quantity",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lotSize",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidMarketStatus",
    inputs: [
      {
        name: "market",
        type: "address",
        internalType: "address",
      },
      {
        name: "actualStatus",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "requiredStatus",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidPositionStatus",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actualStatus",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "expectedStatus",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidTick",
    inputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tickSize",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "LossAlreadyRecognized",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "MarketExpired",
    inputs: [
      {
        name: "expiry",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "currentTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NotConfigurator",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
      {
        name: "configurator",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotController",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
      {
        name: "controller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "NotPositionOwner",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NotReactivityPrecompile",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
      {
        name: "precompile",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ObservationTooSoon",
    inputs: [
      {
        name: "elapsed",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumInterval",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "OpeningCutoffReached",
    inputs: [
      {
        name: "expiry",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "currentTime",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "openingCutoff",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "OracleNotReady",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "age",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumAge",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "OrderDeadlineExceeded",
    inputs: [
      {
        name: "deadlineNs",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximumNs",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "OrderRejected",
    inputs: [
      {
        name: "pool",
        type: "address",
        internalType: "address",
      },
      {
        name: "orderType",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "OrderStateQueryFailed",
    inputs: [
      {
        name: "pool",
        type: "address",
        internalType: "address",
      },
      {
        name: "orderId",
        type: "uint128",
        internalType: "uint128",
      },
    ],
  },
  {
    type: "error",
    name: "PoolRecycled",
    inputs: [
      {
        name: "pool",
        type: "address",
        internalType: "address",
      },
      {
        name: "expectedNonce",
        type: "uint64",
        internalType: "uint64",
      },
      {
        name: "actualNonce",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "PositionDepthExceeded",
    inputs: [
      {
        name: "resultingShares",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximumShares",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "PositionNotFound",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "PositionNotLiquidatable",
    inputs: [
      {
        name: "positionId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "ltvBps",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maintenanceLtvBps",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "QuantityBelowMinimum",
    inputs: [
      {
        name: "quantity",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "QuantizedToZero",
    inputs: [
      {
        name: "requested",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "quantum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "RecoveryExceedsLoss",
    inputs: [
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "requested",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "RepaymentLimitExceeded",
    inputs: [
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ReserveWithdrawalBlocked",
    inputs: [
      {
        name: "debtShares",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "unrecoveredLoss",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "RestingOrder",
    inputs: [
      {
        name: "orderId",
        type: "uint128",
        internalType: "uint128",
      },
    ],
  },
  {
    type: "error",
    name: "SeriesIntervalTooShort",
    inputs: [
      {
        name: "marketId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "interval",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "minimumInterval",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "SeriesPolicyFrozen",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "SeriesPolicyIdentityClaimed",
    inputs: [
      {
        name: "identity",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "SettlementNotFinal",
    inputs: [
      {
        name: "outcomeId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "StaleOracle",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "age",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximumAge",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "TokenApprovalFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        internalType: "address",
      },
      {
        name: "outcomeId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "TokenOperatorApprovalFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "operator",
        type: "address",
        internalType: "address",
      },
      {
        name: "approved",
        type: "bool",
        internalType: "bool",
      },
    ],
  },
  {
    type: "error",
    name: "Unauthorized",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
      {
        name: "requiredRole",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "actualRoles",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "UnsafeModeTransition",
    inputs: [
      {
        name: "currentMode",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "requestedMode",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedCallbackEmitter",
    inputs: [
      {
        name: "emitter",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedDecimals",
    inputs: [
      {
        name: "decimals",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "maximum",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedOrderType",
    inputs: [
      {
        name: "orderType",
        type: "uint8",
        internalType: "uint8",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedSeriesIdentity",
    inputs: [
      {
        name: "identity",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UnsupportedSeriesPolicy",
    inputs: [
      {
        name: "policyId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "UtilizationExceeded",
    inputs: [
      {
        name: "resultingUtilization",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximumUtilization",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ValueOutOfBounds",
    inputs: [
      {
        name: "field",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "maximum",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [
      {
        name: "field",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAmount",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroDenominator",
    inputs: [
      {
        name: "field",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
] as const;
