// GENERATED by scripts/generate-abis.mjs — do not edit.
// Source: contracts/out/IDreamDexMarkOracle.sol/IDreamDexMarkOracle.json

export const oracleAbi = [
  {
    type: "function",
    name: "configurator",
    inputs: [],
    outputs: [
      {
        name: "configurator_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "configureGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "config",
        type: "tuple",
        internalType: "struct OracleConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "minAge",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "updateInterval",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "staleAfter",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "depthQuantity",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "maxObservations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "maxBookLevels",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "conservativeTwap",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "mark",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "age",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "updatedAt",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "disableGeneration",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "generationState",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct OracleConfig",
        components: [
          {
            name: "key",
            type: "tuple",
            internalType: "struct MarketKey",
            components: [
              {
                name: "marketId",
                type: "bytes32",
                internalType: "bytes32",
              },
              {
                name: "pool",
                type: "address",
                internalType: "address",
              },
              {
                name: "marketNonce",
                type: "uint64",
                internalType: "uint64",
              },
              {
                name: "outcomeToken",
                type: "address",
                internalType: "address",
              },
              {
                name: "outcomeId",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "collateral",
                type: "address",
                internalType: "address",
              },
            ],
          },
          {
            name: "minAge",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "updateInterval",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "staleAfter",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "depthQuantity",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "maxObservations",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "maxBookLevels",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "enabled",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
      {
        name: "ring",
        type: "tuple",
        internalType: "struct ObservationRing",
        components: [
          {
            name: "nextIndex",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "cardinality",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "oldestTimestamp",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "newestTimestamp",
            type: "uint40",
            internalType: "uint40",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "module",
    inputs: [],
    outputs: [
      {
        name: "module_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "observationAt",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "index",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    outputs: [
      {
        name: "observation",
        type: "tuple",
        internalType: "struct MarkObservation",
        components: [
          {
            name: "timestamp",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "poolNonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "marketStatus",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "bestBid",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "sameSideDepthBid",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "oppositeSideDepthAsk",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "conservativeMark",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "cumulativeMarkSeconds",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "observe",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "observation",
        type: "tuple",
        internalType: "struct MarkObservation",
        components: [
          {
            name: "timestamp",
            type: "uint40",
            internalType: "uint40",
          },
          {
            name: "poolNonce",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "marketStatus",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "bestBid",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "sameSideDepthBid",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "oppositeSideDepthAsk",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "conservativeMark",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "cumulativeMarkSeconds",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "GenerationConfigured",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GenerationDisabled",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ObservationRecorded",
    inputs: [
      {
        name: "generationKey",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "index",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "timestamp",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
      {
        name: "conservativeMark",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
] as const;
